#!/usr/bin/python3

# break OAPATH target
# skip_src   a1 a2a a2b a3 b1b b2b   splits_folder splits_format_ext splits_printf_ext   allow_untranslated
# skip_comp   compiler   header  no_diagnostics  no_confirm ffdec  no_clean

import sys
if len(sys.argv)!=3:
	print('Usage: as3.py output_folder output_file')
	exit(1)

import os

OAPATH=""
if os.environ.get('OAPATH'):
	OAPATH=os.environ.get('OAPATH')
	#this is windows specific os.add_dll_directory(os.environ.get('OAPATH'))

import ctypes
try: #in LD_LIBRARY_PATH
	lib=ctypes.cdll.LoadLibrary(os.path.join(OAPATH,"liboaas.so"))
except Exception:
	try:
		lib=ctypes.cdll.LoadLibrary(os.path.join(OAPATH,"liboaas.dll"))
	except Exception:
		lib = None
		# print('no liboaas support')
if lib:
	try:
		lib.line.argtypes = [ctypes.c_char_p]; lib.line.restype = ctypes.c_char_p
		lib.startline.argtypes = [ctypes.c_char_p,ctypes.c_char_p]; lib.startline.restype = ctypes.c_char_p
		lib.ratio.argtypes = [ctypes.c_char]; lib.ratio.restype = ctypes.c_char
		lib.flash_to_openfl.argtypes = [ctypes.c_char]
	except Exception:
		print('lib oaas error')
		exit(1)

if os.environ.get('break'):
	import pdb; pdb.set_trace()

dest=sys.argv[1]
def hx_ext(fl):
	return os.path.join(dest,os.path.basename(os.path.dirname(fl))+'.hx')
out_file_name=sys.argv[2]

target=os.environ.get('target')
if target:
	if target!="html5":
		print('target not available')
		exit(1)

if not os.environ.get('skip_src'):
	if target:
		if lib:
			lib.flash_to_openfl(True)

	def changeable(a,b,c): globals()[a + b] = c if os.environ.get(a + b) == None else os.environ.get(a + b)
	changeable('a','1','/')
	changeable('a','2a','/')
	changeable('a','2b','*')
	changeable('a','3','3')
	changeable('b','1b','*')
	changeable('b','2b','/')

	def premade_formats():
		#environ or defaults at edor and src

		splits_folder=os.environ.get('splits_folder')
		if not splits_folder:
			splits_folder='osrc'

		splits_format_ext=os.environ.get('splits_format_ext')
		if not splits_format_ext:
			splits_format_ext='split'

		#and here at src
		splits_printf_ext=os.environ.get('splits_printf_ext')
		if not splits_printf_ext:
			splits_printf_ext='format'

		def ext(a): return '' if a=='' else os.extsep+a     #notice: os.extsep is not directly connected with my edor and src, is like a guardian?
		a=('' if splits_folder=='' else splits_folder+os.sep)

		return (a+os.path.splitext(out_file_name)[0]+ext(splits_format_ext),a+out_file_name+ext(splits_printf_ext))

	allow_untranslated=os.environ.get('allow_untranslated')
	def singleline():
		bf=chars[:pos]
		if lib:
			bf = bf.rstrip(b"\r\n") #this is extra at inline comments
			byts = bytes(bf)
			if len(stored):
				bf=lib.startline(bytes(stored),byts)
				stored.clear()
			else:
				bf=lib.line(byts)
			if not allow_untranslated:
				if byts == bf:
					r = lib.ratio(False)
					if ord(r) !=  100: #can be blank closing comment
						print("Untranslated. 'if not os.environ.get('allow_untranslated') failed")
						exit(1)
			dfile.write(bf)
			dfile.write(os.linesep.encode())
		else:
			dfile.write(bf)

	splits_file, splits_mix = premade_formats()

	try:
		os.mkdir(dest)
	except FileExistsError:
		pass

	#for filename in os.listdir(src):
	with open(splits_file) as splits_file:
		splits_file_data=splits_file.read()
		with open(splits_mix) as splits_mix:
			splits_mix_data=splits_mix.read()

			files = splits_file_data.split('\x00')
			files.pop() # Remove the last empty string
			texts = splits_mix_data.split('\x00')
			texts.pop()
			i=0

			multiline_backjump=len(b1b.encode())+len(b2b.encode())

			stored=bytearray()
			multiline_backjump_start=len(a1.encode())+len(a3.encode())
			singleline_backjump_start=multiline_backjump_start
			multiline_backjump_start+=len(a2a.encode())
			singleline_backjump_start+=len(a2b.encode())

			was_multiline=False
			for f in files:
				if texts[i]:
					text=texts[i]
				else:
					with open(f) as sfile:
						text=sfile.read()
				text=text.splitlines(keepends=True)
				with open(hx_ext(f),'ab') as dfile: #haxe will not do for .as
					mode=0
					for line in text:
						chars = bytearray(len(line.encode())) #'utf-8'
						pos = 0
						for c in line:
							ch=c.encode()
							positions=len(ch)
							for j in range(0,positions):
								chars[pos]=ch[j]
								pos+=1
							if mode==0:
								if c==a1:
									mode=1
							elif mode==1:
								if c==a2a:
									mode=2
								elif c==a2b:
									mode=3
								else:
									mode=0
							elif mode==2 or mode==3:
								if c==a3:
									if mode==2:
										xpos=singleline_backjump_start
									else:
										xpos=multiline_backjump_start
									stored=chars[:pos-xpos]
									mode*=2
									pos=0    #notice: both //3 and /*3 will reset the line
								else:
									mode=0
							elif mode==6:
								if c==b1b:
									mode=7
							elif mode==7:
								if c==b2b:
									mode=0
									pos-=multiline_backjump
									singleline()
									pos=0
									was_multiline=True
								else:
									mode=6
						if mode==4:
							mode=0
							singleline()
						elif mode==6:
							singleline()
						else:
							bf=chars[:pos]
							if not was_multiline:
								dfile.write(bf)
							else:
								bf=bf.rstrip(b"\r\n") #was already added one separator
								dfile.write(bf)
								was_multiline=False
					#here can test if multiline was closed
				i=i+1
			if lib:
				lib.ratio(True)

if not os.environ.get('skip_comp'):
	import subprocess
	def srun(a,capture_output=False):
		r=subprocess.run(a,capture_output=capture_output)
		if r.returncode:
			print('error')
			exit(r.returncode)
		return r
	compiler=os.environ.get('compiler')
	if not target:
		if not compiler:
			compiler='haxe'

		c_dir=os.getcwd() #haxe says no to abs path
		dest_file=os.path.realpath(out_file_name)
		os.chdir(dest)
		hd=os.environ.get('header')
		baser=[compiler,'-swf',dest_file,'-main','Main']
		if hd:
			baser.extend(['-swf-header',hd])
			# -swf-header 960:640:60:f68712 -swf-version 15
			#w:h:fps:rgb
		if os.environ.get('no_diagnostics'):
			srun(baser)
		else:
			baser.extend(['--display','diagnostics'])
			p=srun(baser,capture_output=True)
			import json
			diagnostics = json.loads(p.stderr)
			for file in diagnostics:
				for d in file["diagnostics"]:
					if d["severity"] == 1 and d["kind"] == 7:
						f=d["args"]["moduleType"]["name"]
						n=d["args"]["entries"][0]["fields"][0]["field"]["name"]
						l=d["range"]["start"]["line"]
						#now is like: fix one error will fix another 4
						print(f+' '+str(l)+' '+n)
						#print(json.dumps(d,indent=10))
						#os.execv(sys.executable, [sys.executable] + sys.argv)
						#print("never reached")
						exit(1)

		#done for output_folder
		os.chdir(c_dir) #back for clean, and maybe ffdec is relative, dest_file is realpath

		if not os.environ.get('no_confirm'):
			#confirm is as3

			dest_file_tmp=dest_file+'.tmp'
			ffdec=os.environ.get('ffdec')
			if not ffdec:
				ffdec='ffdec'
			srun([ffdec,'-decompress',dest_file,dest_file_tmp])
			with open(dest_file_tmp,'rb') as file:
				file.seek(8)
				#rect
				b=file.read(1)
				n=b[0]>>3 # 0xff >> 1 is 0x7f
				n=5+(n*4)
				if n%8:
					n=int(n/8)+1
				else:
					n=n/8
				file.seek(n+3,1)
				#tag
				tag=file.read(2)
				tg=tag[1]<<2
				tg_low=tag[0]>>6
				tg|=tg_low
				if tg!=69:
					print('no FileAttributes tag')
					exit(1)
				tg=tag[0]&0x3f
				if tg==0x3f:
					print('malformed FileAttributes tag')
					exit(1)
				#tag data
				tg=file.read(1)
				if (tg[0]&8)==0:
					print('ActionScript3 bit is not set')
					exit(1)

			os.remove(dest_file_tmp)

		if not os.environ.get('no_clean'):
			for f in files:
				os.remove(hx_ext(f))
			os.rmdir(dest)

	else:
		if not compiler:
			compiler='openfl'
		srun([compiler,'build','html5'])
