#!/usr/bin/python3

# break OAPATH target src_name
# a1 a2a a2b a3 b1b b2b  splits_folder splits_format_ext splits_printf_ext

# skip_orig mirror_name
# skip_src allow_untranslated verbose
# skip_comp  compiler  SERVER_PID header  no_diagnostics only_diagnostics dump OACACHE  no_confirm ffdec  no_clean

# / / 3
#   *   * /

#import ctypes
#import difflib
#import json
#import os
from pathlib import Path
#import pdb
#import signal
#import shutil
#import socket
#import subprocess
import sys
#import time

if len(sys.argv)!=3:
	print(f"Usage: {Path(sys.argv[0]).name} output_folder output_file")
	exit(1)

import os

OAPATH=""
if os.environ.get('OAPATH'):
	OAPATH=os.environ.get('OAPATH')
	#this is windows specific os.add_dll_directory(os.environ.get('OAPATH'))

import ctypes
try: #in LD_LIBRARY_PATH
	lib=ctypes.cdll.LoadLibrary(os.path.join(OAPATH,"liboaas.so"))
except Exception:
	try:
		lib=ctypes.cdll.LoadLibrary(os.path.join(OAPATH,"liboaas.dll"))
	except Exception:
		lib = None
		# print('no liboaas support')
if lib:
	try:
		lib.line.argtypes = [ctypes.c_char_p]; lib.line.restype = ctypes.c_char_p
		lib.startline.argtypes = [ctypes.c_char_p,ctypes.c_char_p]; lib.startline.restype = ctypes.c_char_p
		lib.ratio.argtypes = [ctypes.c_char]; lib.ratio.restype = ctypes.c_char
		lib.verbose.argtypes = [ctypes.c_char]
		lib.flash_to_openfl.argtypes = [ctypes.c_char]
		lib.solve.argtypes = [ctypes.c_char_p,ctypes.c_char_p]; lib.solve.restype = ctypes.c_char_p
	except Exception:
		print('lib oaas error')
		exit(1)

if os.environ.get('break'):
	import pdb; pdb.set_trace()

dest=sys.argv[1]
def hx_ext(fl):
	return os.path.join(dest,os.path.basename(os.path.dirname(fl))+'.hx')
out_file_name=sys.argv[2]

def changeable(a,b,c): globals()[a + b] = c if os.environ.get(a + b) == None else os.environ.get(a + b)
changeable('a','1','/')
changeable('a','2a','/')
changeable('a','2b','*')
changeable('a','3','3')
changeable('b','1b','*')
changeable('b','2b','/')
def premade_formats():
	#environ or defaults at edor and src

	splits_folder=os.environ.get('splits_folder')
	if not splits_folder:
		splits_folder='osrc'

	splits_format_ext=os.environ.get('splits_format_ext')
	if not splits_format_ext:
		splits_format_ext='split'

	#and here at src
	splits_printf_ext=os.environ.get('splits_printf_ext')
	if not splits_printf_ext:
		splits_printf_ext='format'

	def ext(a): return '' if a=='' else os.extsep+a     #notice: os.extsep is not directly connected with my edor and src, is like a guardian?
	a=('' if splits_folder=='' else splits_folder+os.sep)

	return (a+os.path.splitext(out_file_name)[0]+ext(splits_format_ext),a+out_file_name+ext(splits_printf_ext))
def splits_data(mix=False,orig=False):
	splits_file, splits_mix = premade_formats()
	#for filename in os.listdir(src):
	with open(splits_file) as splits_file:
		splits_file_data=splits_file.read()
		with open(splits_mix) as splits_mix:
			splits_mix_data=splits_mix.read()

			files = splits_file_data.split('\x00')
			files.pop() # Remove the last empty string
			files_src = [str(Path(src_name)) + os.sep + str(Path(*Path(f).parts[1:])) for f in files]
			if not mix:
				if not orig:
					return files_src
				files_mirror = [str(Path(mirror_name)) + os.sep + str(Path(*Path(f).parts[1:])) for f in files]
				return (files,files_mirror,files_src)

			texts = splits_mix_data.split('\x00')
			texts.pop()

			return (files_src,texts)

target=os.environ.get('target')
if target:
	if target!="html5":
		print('target not available')
		exit(1)

src_name=os.environ.get('src_name')
if not src_name:
	src_name='src'

import shutil

skip_orig='skip_orig'
if not os.environ.get(skip_orig):
	mirror_name=os.environ.get('mirror_name')
	if not mirror_name:
		mirror_name='mirror'

	files,files_mirror,files_src = splits_data(orig=True)

	import difflib

	for i, f in enumerate(files):
		orig = Path(f)
		mirror = Path(files_mirror[i])
		src = Path(files_src[i])
		if not mirror.exists():
			# create parent folders
			mirror.parent.mkdir(parents=True, exist_ok=True)
			src.parent.mkdir(parents=True, exist_ok=True)

			# create mirror copy
			shutil.copy(orig, mirror) # or copy2: Identical to copy() except that copy2() also attempts to preserve file metadata.

			# create src copy
			shutil.copy(orig, src)
		else:
			old = mirror.read_text().splitlines(keepends=True)
			new = orig.read_text().splitlines(keepends=True)
			out = src.read_text().splitlines(keepends=True)
			matcher = difflib.SequenceMatcher(None, old, new)
			offset = 0
			#        old     new
			for tag, i1, i2, j1, j2 in matcher.get_opcodes():
				if tag == "equal":
					continue
				print(tag)
				print("old:", old[i1:i2])
				print("new:", new[j1:j2])

				i1 += offset
				i2 += offset
				if tag == "insert":
					out[i1:i1] = new[j1:j2]
					offset += (j2 - j1)
					continue
				if tag == "replace":
					out[i1:i2] = new[j1:j2]
					offset += (j2 - j1) - (i2 - i1)
					continue
				if tag == "delete":
					del out[i1:i2]
					offset -= (i2 - i1)
					continue
				print('?')
				exit(1)
			src.write_text(''.join(out))#os.linesep
			mirror.write_text(''.join(new))

terminations="\r\n"

skip_src='skip_src'
if not os.environ.get(skip_src):
	if lib:
		if target:
			lib.flash_to_openfl(True)
		if os.environ.get('verbose'):
			lib.verbose(True)

	allow_untranslated=os.environ.get('allow_untranslated')
	def singleline():
		bf=chars[:pos]
		if lib:
			bf = bf.rstrip(terminations.encode()) #this is extra at inline comments
			byts = bytes(bf)
			if len(stored):
				bf=lib.startline(bytes(stored),byts)
				stored.clear()
			else:
				bf=lib.line(byts)
			if not allow_untranslated:
				if byts == bf:
					r = lib.ratio(False)
					if ord(r) !=  100: #can be blank closing comment
						print("Untranslated. 'if not os.environ.get('allow_untranslated') failed")
						exit(1)
			dfile.write(bf)
			dfile.write(os.linesep.encode())
		else:
			dfile.write(bf)

	try:
		os.mkdir(dest)
	except FileExistsError:
		pass

	files,texts = splits_data(mix=True)
	i=0

	multiline_backjump=len(b1b.encode())+len(b2b.encode())

	stored=bytearray()
	multiline_backjump_start=len(a1.encode())+len(a3.encode())
	singleline_backjump_start=multiline_backjump_start
	multiline_backjump_start+=len(a2a.encode())
	singleline_backjump_start+=len(a2b.encode())

	was_multiline=False
	for f in files:
		if texts[i]:
			text=texts[i]
		else:
			with open(f) as sfile:
				text=sfile.read()
		text=text.splitlines(keepends=True)
		with open(hx_ext(f),'ab') as dfile: #haxe will not do for .as
			mode=0
			for line in text:
				chars = bytearray(len(line.encode())) #'utf-8'
				pos = 0
				for c in line:
					ch=c.encode()
					positions=len(ch)
					for j in range(0,positions):
						chars[pos]=ch[j]
						pos+=1
					if mode==0:
						if c==a1:
							mode=1
					elif mode==1:
						if c==a2a:
							mode=2
						elif c==a2b:
							mode=3
						else:
							mode=0
					elif mode==2 or mode==3:
						if c==a3:
							if mode==2:
								xpos=singleline_backjump_start
							else:
								xpos=multiline_backjump_start
							stored=chars[:pos-xpos]
							mode*=2
							pos=0    #notice: both //3 and /*3 will reset the line
						else:
							mode=0
					elif mode==6:
						if c==b1b:
							mode=7
					elif mode==7:
						if c==b2b:
							mode=0
							pos-=multiline_backjump
							singleline()
							pos=0
							was_multiline=True
						else:
							mode=6
				if mode==4:
					mode=0
					singleline()
				elif mode==6:
					singleline()
				else:
					bf=chars[:pos]
					if not was_multiline:
						dfile.write(bf)
					else:
						bf=bf.rstrip(terminations.encode()) #was already added one separator
						dfile.write(bf)
						was_multiline=False
			#here can test if multiline was closed
		i=i+1
	if lib:
		lib.ratio(True)

if not os.environ.get('skip_comp'):
	import subprocess
	def srun(a):
		r=subprocess.run(a)
		if r.returncode:
			print('error')
			exit(r.returncode)
	compiler=os.environ.get('compiler')
	if not target:
		if not compiler:
			compiler='haxe'

		c_dir=os.getcwd() #haxe says no to abs path
		dest_file=os.path.realpath(out_file_name)

		import signal
		def stop_server():
			pid=int(server_pid)
			try:
				os.kill(pid, signal.SIGTERM) #async
			except ProcessLookupError:
				return
			try:
				os.kill(pid, 0)  # signal 0 = just checks if it's alive
			except ProcessLookupError:
				return
			time.sleep(1)
			try:
				os.kill(pid, 0)
			except ProcessLookupError:
				return
			try:
				os.kill(pid, signal.SIGKILL)
			except ProcessLookupError:
				return
		def exiting():
			stop_server()
			exit(1)

		import time

		os.chdir(dest)
		server_pid=os.environ.get('SERVER_PID')
		if not server_pid:
			import socket
			server = subprocess.Popen([compiler, "--wait", "6000"])
			server_pid=str(server.pid)
			try:
				with socket.create_connection(("127.0.0.1", 6000), timeout=1):
					pass
			except OSError:
				time.sleep(1)
				try:
					with socket.create_connection(("127.0.0.1", 6000), timeout=1):
						pass
				except OSError:
					print('server error')
					exiting()

		baser=[compiler,'--connect','6000','-swf',dest_file,'-main','Main','-D','flash_strict']
		#                                                                   this flag for _x to be error

		hd=os.environ.get('header')
		if hd:
			baser.extend(['-swf-header',hd])
			# -swf-header 960:640:60:f68712 -swf-version 15
			#w:h:fps:rgb

		def crun(a,capture_output=False):
			r=subprocess.run(a,capture_output=capture_output)
			if r.returncode:
				print('error')
				exiting()
			return r

		OACACHE=os.environ.get('OACACHE')
		if not OACACHE:
			OACACHE="__oaas__"
		o_d=os.environ.get('only_diagnostics')
		if os.environ.get('no_diagnostics'):
			crun(baser)
		else:
			if not o_d:
				r=subprocess.run(baser)
			if o_d or r.returncode:
				baser.extend(['--display','diagnostics'])
				p=crun(baser,capture_output=True)

				def diags(diagnostics):
					def save_line(module, line):
						folder = Path(OACACHE)
						folder.mkdir(exist_ok=True)
						file = folder / module  # this is not + , on windows is backslash
						if file.exists():
							old_line = file.read_text()
							if old_line == str(line):
								return False
						file.write_text(str(line))
						return True
					dump=os.environ.get('dump')
					for file in diagnostics:
						for d in file["diagnostics"]:
							if d["severity"] == 1 and d["kind"] in [2,7]:
								if dump:
									print(json.dumps(d,indent=10))
								# this is unstable: module=d["args"]["moduleType"]["name"]
								field=d["args"]["entries"][0]["fields"][0]["field"]
								module=os.path.splitext(field["pos"]["file"])[0]
								positions=d["range"]["end"]
								line=positions["line"]
								value=field["name"]
								print(module+' '+str(line)+' '+value)

								#now is like: fix one error will fix another 4

								os.chdir(c_dir) #back to original folder
								files=splits_data()
								for f in files:
									mod = os.path.basename(os.path.dirname(f))
									if mod == module:
										if not lib:
											print('missing oaas lib')
											exiting()
										with open(f) as file:
											lines = file.readlines()
										linestr = lines[line]

										solved = lib.solve(value.encode(),linestr[positions["character"]+1:].encode())

										if not solved:
											exiting()
										if linestr[-1] in terminations:
											linestr = linestr.rstrip(terminations)
											has_term=True
										else:
											has_term=False
										if save_line(module,line):
											linestr = linestr + a1 + a2a + a3 + solved.decode() + (os.linesep if has_term else "")
										else:
											linestr = linestr + '+' + solved.decode() + (os.linesep if has_term else "")
										lines[line] = linestr

										with open(f,"w") as file:
										    file.writelines(lines)

										if not o_d:
											for f in files:
												os.remove(hx_ext(f))
											os.environ[skip_orig] = "1"
											os.environ["SERVER_PID"] = server_pid
											os.execv(sys.executable, [sys.executable] + sys.argv)
											#print("never reached")
										return
					print("diagnostics failed")
					exiting()

				import json
				diags(json.loads(p.stderr))

		stop_server()
		#done for output_folder
		os.chdir(c_dir) #back for clean, and maybe ffdec is relative, dest_file is realpath

		if not os.environ.get('no_confirm') and not o_d: #only diagnostics is a dry run at haxe
			#confirm is as3

			dest_file_tmp=dest_file+'.tmp'
			ffdec=os.environ.get('ffdec')
			if not ffdec:
				ffdec='ffdec'
			srun([ffdec,'-decompress',dest_file,dest_file_tmp])
			with open(dest_file_tmp,'rb') as file:
				file.seek(8)
				#rect
				b=file.read(1)
				n=b[0]>>3 # 0xff >> 1 is 0x7f
				n=5+(n*4)
				if n%8:
					n=int(n/8)+1
				else:
					n=n/8
				file.seek(n+3,1)
				#tag
				tag=file.read(2)
				tg=tag[1]<<2
				tg_low=tag[0]>>6
				tg|=tg_low
				if tg!=69:
					print('no FileAttributes tag')
					exit(1)
				tg=tag[0]&0x3f
				if tg==0x3f:
					print('malformed FileAttributes tag')
					exit(1)
				#tag data
				tg=file.read(1)
				if (tg[0]&8)==0:
					print('ActionScript3 bit is not set')
					exit(1)

			os.remove(dest_file_tmp)

		if not os.environ.get('no_clean'):
			files=splits_data() #if not files , are also at: orig src diagnostics
			for f in files:
				os.remove(hx_ext(f))
			os.rmdir(dest)
			shutil.rmtree(OACACHE, ignore_errors=True)

	else:
		if not compiler:
			compiler='openfl'
		srun([compiler,'build','html5'])
