#!/bin/sh
if [ -n "${VISUAL}" ]; then
  exec ${VISUAL} "$@"
elif [ -n "${EDITOR}" ]; then
  exec ${EDITOR} "$@"
elif type sensible-editor >/dev/null 2>/dev/null; then
  exec sensible-editor "$@"
fi
editors='nano editor vi ex'
for x in ${editors}; do
  if type "${x}" >/dev/null 2>/dev/null; then
    exec "${x}" "$@"
  fi
done
#${DISPLAY} for gui, ex, edit, cmd=$(xdg-mime query default ) 2>/dev/null; [ -n "$cmd" ]
