#!/bin/sh
if [ -z "$p" ]; then
	p=python3
fi
if [ -e dest ] && [ -z "${skip_src}" ]; then
	rm -rf dest/* __oacache__/*
fi
if [ -z "${OAPATH}" ]; then
	export OAPATH=../../oaas
fi
if [ -z "${verbose+x}" ]; then
	verbose=x
	echo verbose
fi
if [ -z "${clean}" ]; then no_clean=x; fi
no_clean=${no_clean} verbose=${verbose} header=550:400:12:ffFFff $p ../../oaas3 dest a.swf && {
	at_folder=../ . ../integ && {
		${RUN__SHELL} ./df
		exit
	}
	echo all good
}
