#!/bin/bash
if [ -z "${LD_LIBRARY_PATH}" ]; then LD_LIBRARY_PATH=../../src; fi
isdebug=x _L=../ ${SHELL} ../asv && \
extra=x isdebug=x _L=../ ${SHELL} ../asv && \
LD_LIBRARY_PATH=${LD_LIBRARY_PATH} ${SHELL} ../../oaalternative a.swf "./a.out x x" && cat a.swf.log
