#!/bin/sh
if [ -z "${LD_LIBRARY_PATH}" ]; then LD_LIBRARY_PATH=../../src; fi
is_debug=x _L=../ ${RUN__SHELL} ../asv && \
extra=x is_debug=x _L=../ ${RUN__SHELL} ../asv && \
#expect_obfuscation=./q   this is solved since ffdec_24.1.1_nightly3382
LD_LIBRARY_PATH=${LD_LIBRARY_PATH} deobfuscator_launcher=python3 ${RUN__SHELL} ../../oaalternative.sh a.swf "./a.out x x" && cat a.swf.log

# ffdec=/home/bc/a/ffdec/bin/ffdec ./as
# ffdec=/home/bc/a/ffdec/j12/usr/bin/ffdec FFDEC_JARFILENAME=../../../../ffdec/j12/usr/share/java/ffdec/ffdec.jar ./as
