on:
 workflow_dispatch:

jobs:
 bbuild:
  runs-on: windows-latest
  steps:
   - uses: actions/checkout@v4
   - shell: pwsh
     run: |
      & { Invoke-Expression (Get-Content -Raw ./oaalternative.cmd) }
      echo ok
   - shell: cmd
     run: |
      call oaalternative.cmd
      echo ok
      exit /b 0
   - shell: bash
     run: |
      /bin/bash ./oaalternative.cmd
   - shell: sh
     run: |
      /bin/sh ./oaalternative.cmd
