on:
 workflow_dispatch:

jobs:
 bbuild:
  runs-on: windows-latest
  steps:
   - uses: actions/checkout@v4
   - shell: pwsh
     run: |
      & { Invoke-Expression (Get-Content -Raw ./oaalternative.cmd) }
      echo ok
   - shell: cmd
     run: |
      call oaalternative.cmd
      echo ok
      exit /b 0
   - shell: bash
     run: |
      touch a.a.log
      mkdir a
      skip_ffdec=x /bin/bash oaalternative.cmd a.a
      echo ok
   - shell: sh
     run: |
      skip_ffdec=x /bin/sh oaalternative.cmd a.a
      echo ok
